# http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
shallow_clone: true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 2

cache:
  - node_modules                    # local npm modules
  - '%APPDATA%\npm-cache'           # npm cache

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - node --version
  - npm --version
  - npm test
